apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  resources:
    inputs:
      - name: repo
        type: git

  steps:

    - name: build-buildkit
      image: moby/buildkit:v0.10.3
      securityContext:
        privileged: true
      env:
        # needs resolve ownership of mounted git and docker config etc
        # - name: BUILDKITD_FLAGS
        #   value: --oci-worker-no-process-sandbox
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        # https://github.com/moby/buildkit#daemonless
        - buildctl-daemonless.sh
        - build
        - --frontend=dockerfile.v0
        - --local=context=/workspace/repo/src
        - --local=dockerfile=/workspace/repo/src
        - --output=type=image,\"name=docker.io/russtanevich/private:d001,docker.io/russtanevich/private:latest\",push=true
        - --export-cache=type=inline
        - --import-cache=type=registry,ref=docker.io/russtanevich/private

    - name: ensure-base-image-pulled
      image: gcr.io/kaniko-project/warmer:v1.8.1
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/warmer
        # https://github.com/GoogleContainerTools/kaniko/issues/1142
        - --image=ubuntu:22.04
        - --cache-dir=/workspace/cache

    # https://github.com/GoogleContainerTools/kaniko/issues/875
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.8.1
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo/src
        # https://github.com/GoogleContainerTools/kaniko/issues/524#issuecomment-455780091
        - --destination=russtanevich/private:k001
        # https://github.com/GoogleContainerTools/kaniko#caching
        - --cache-repo=russtanevich/private
        - --cache=true
        - --cache-dir=/workspace/cache

  workspaces:
    - name: cached-dir
      optional: true
      mountPath: /workspace/cache