apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-and-push
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-and-push
  resources:
    inputs:
      - name: repo
        resourceRef:
          name: russtanevich-tekton-example

  workspaces:
    - name: cached-dir
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
